name: CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag suranagivinod/fastapi:latest
    - name: Publish image
      run: docker push suranagivinod/fastapi:latest
